// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan CollectiveExternalLink, corresponding to Stack Exchange API v2's collective_external_link type
    /// http://api.stackexchange.com/docs/types/collective-external-link
    /// </summary>
    public partial class CollectiveExternalLink : StacManType
    {
        /// <summary>
        /// type -- introduced in API version 2.3
        /// </summary>
        [Field("type")]
        public string Type { get; internal set; }

        /// <summary>
        /// link -- introduced in API version 2.3
        /// </summary>
        [Field("link")]
        public string Link { get; internal set; }

    }
}
