// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan CollectiveReport, corresponding to Stack Exchange API v2's collective_report type
    /// http://api.stackexchange.com/docs/types/collective-report
    /// </summary>
    public partial class CollectiveReport : StacManType
    {
        /// <summary>
        /// activity_report_dimensions -- introduced in API version 2.3
        /// </summary>
        [Field("activity_report_dimensions")]
        public Collectives.ReportDimension[] ActivityReportDimensions { get; internal set; }

        /// <summary>
        /// collective -- introduced in API version 2.3
        /// </summary>
        [Field("collective")]
        public Collective Collective { get; internal set; }

        /// <summary>
        /// creation_date -- introduced in API version 2.3
        /// </summary>
        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        /// <summary>
        /// dimensions -- introduced in API version 2.3
        /// </summary>
        [Field("dimensions")]
        public string[] Dimensions { get; internal set; }

        /// <summary>
        /// download_link -- introduced in API version 2.3
        /// </summary>
        [Field("download_link")]
        public string DownloadLink { get; internal set; }

        /// <summary>
        /// end_date -- introduced in API version 2.3
        /// </summary>
        [Field("end_date")]
        public DateTime EndDate { get; internal set; }

        /// <summary>
        /// health_report_dimensions -- introduced in API version 2.3
        /// </summary>
        [Field("health_report_dimensions")]
        public Collectives.ReportDimension[] HealthReportDimensions { get; internal set; }

        /// <summary>
        /// included_tags -- introduced in API version 2.3
        /// </summary>
        [Field("included_tags")]
        public string[] IncludedTags { get; internal set; }

        /// <summary>
        /// metrics -- introduced in API version 2.3
        /// </summary>
        [Field("metrics")]
        public string[] Metrics { get; internal set; }

        /// <summary>
        /// name -- introduced in API version 2.3
        /// </summary>
        [Field("name")]
        public string Name { get; internal set; }

        /// <summary>
        /// report_id -- introduced in API version 2.3
        /// </summary>
        [Field("report_id")]
        public int? ReportId { get; internal set; }

        /// <summary>
        /// report_type -- introduced in API version 2.3
        /// </summary>
        [Field("report_type")]
        public Collectives.ReportType ReportType { get; internal set; }

        /// <summary>
        /// start_date -- introduced in API version 2.3
        /// </summary>
        [Field("start_date")]
        public DateTime StartDate { get; internal set; }

        /// <summary>
        /// state -- introduced in API version 2.3
        /// </summary>
        [Field("state")]
        public Collectives.ReportState State { get; internal set; }

        /// <summary>
        /// users_report_dimensions -- introduced in API version 2.3
        /// </summary>
        [Field("users_report_dimensions")]
        public Collectives.ReportDimension[] UsersReportDimensions { get; internal set; }

    }
}
