// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Collective, corresponding to Stack Exchange API v2's collective type
    /// http://api.stackexchange.com/docs/types/collective
    /// </summary>
    public partial class Collective : StacManType
    {
        /// <summary>
        /// description -- introduced in API version 2.3
        /// </summary>
        [Field("description")]
        public string Description { get; internal set; }

        /// <summary>
        /// external_links -- introduced in API version 2.3
        /// </summary>
        [Field("external_links")]
        public CollectiveExternalLink[] ExternalLinks { get; internal set; }

        /// <summary>
        /// link -- introduced in API version 2.3
        /// </summary>
        [Field("link")]
        public string Link { get; internal set; }

        /// <summary>
        /// name -- introduced in API version 2.3
        /// </summary>
        [Field("name")]
        public string Name { get; internal set; }

        /// <summary>
        /// slug -- introduced in API version 2.3
        /// </summary>
        [Field("slug")]
        public string Slug { get; internal set; }

        /// <summary>
        /// tags -- introduced in API version 2.3
        /// </summary>
        [Field("tags")]
        public string[] Tags { get; internal set; }

    }
}
