// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan CollectiveMembership, corresponding to Stack Exchange API v2's collective_membership type
    /// http://api.stackexchange.com/docs/types/collective-membership
    /// </summary>
    public partial class CollectiveMembership : StacManType
    {
        /// <summary>
        /// collective -- introduced in API version 2.3
        /// </summary>
        [Field("collective")]
        public Collective Collective { get; internal set; }

        /// <summary>
        /// role -- introduced in API version 2.3
        /// </summary>
        [Field("role")]
        public Collectives.Role Role { get; internal set; }

    }
}
